name: hid_linux
description: Linux implementation of the hid plugin.
version: 0.1.0
repository: https://github.com/rustui/hid/tree/main/hid_linux

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2
  hid_platform_interface: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    implements: hid
    platforms:
      linux:
        dartPluginClass: HidPluginLinux
